packages:
  - src/*
  - fixtures/*

catalogs:
  cli:
    '@antfu/ni': 24.4.0
    '@isentinel/eslint-config': 1.2.6
    '@typescript-eslint/eslint-plugin': 8.32.1
    '@typescript-eslint/parser': 8.32.1
    '@typescript-eslint/type-utils': 8.32.1
    '@typescript-eslint/utils': 8.32.1
    bumpp: 10.1.1
    eslint-plugin-pnpm: 0.3.1
    eslint: 9.30.0
    jiti: 2.4.2
    lint-staged: 16.0.0
    simple-git-hooks: 2.13.0
    ts-api-utils: 2.1.0
    tsdown: 0.11.12
    tsx: 4.19.4
    typescript: 5.8.3
  testing:
    eslint-8: npm:eslint@^8.57.0
    eslint-plugin-eslint-plugin: 6.4.0
    eslint-vitest-rule-tester: 2.2.0
    publint: 0.3.12
    unplugin-unused: 0.5.0
    vitest: 3.1.4
  types:
    '@rbxts/compiler-types': 3.0.0-types.0
    '@rbxts/types': 1.0.853
    '@types/node': 22.15.19
  utils:
    eslint-doc-generator: 2.2.2

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

configDependencies:
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependencies:
  - unrs-resolver
