packages:
  - src/*

catalogs:
  dev:
    '@antfu/ni': 24.3.0
    '@isentinel/eslint-config': 1.1.2
    '@typescript-eslint/eslint-plugin': 8.32.0
    '@typescript-eslint/parser': 8.32.0
    '@typescript-eslint/utils': 8.32.0
    '@typescript-eslint/type-utils': 8.32.0
    bumpp: 10.1.0
    eslint-plugin-pnpm: 0.3.1
    eslint: 9.26.0
    jiti: 2.4.2
    lint-staged: 15.5.2
    simple-git-hooks: 2.13.0
    ts-api-utils: 2.1.0
    tsx: 4.19.4
    typescript: 5.8.3
    unbuild: 3.5.0
  testing:
    eslint-plugin-eslint-plugin: 6.4.0
    eslint-vitest-rule-tester: 2.2.0
    vitest: 3.1.3
    yaml: 2.7.1
  types:
    '@rbxts/compiler-types': 3.0.0-types.0
    '@rbxts/types': 1.0.852
    '@types/node': 22.15.17
  utils:
    eslint-doc-generator: 2.1.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
